### ISSUE TITLE
Finish deployment scripts

### ISSUE THREAD

**Issue by HughPowell** [impact48/PurpleFriday#4]
- Add users to run the apps rather than `root`
- Set the working directory properly

Help can be found here : https://blog.todotnet.com/2017/07/publishing-and-running-your-asp-net-core-project-on-linux/

**Comment by parsfan82** [comment]
Resolved as part of introduction of deployment script:

ce7f8d4 Sat Aug 10 22:47:24 2019 +0100 -  - Deployment scripts <lloyds>
